routes/web.php
<?php

use App\Http\Controllers\Admin\PemasanganController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\GeoJsonController;
use App\Http\Controllers\JaringanPipaController;
use App\Http\Controllers\PelaporanController;
use App\Http\Controllers\PemasanganController as PublicPemasanganController;
use App\Http\Controllers\PelaporanController as PublicPelaporanController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\TitikAssesorisController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'frontend/index')->name('home');

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'authenticate'])->name('authenticate');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

// Route::get('/register', [RegisterController::class, 'index'])->name('register');
// Route::post('/register', [RegisterController::class, 'store'])->name('createUser');


//Post
// Route::get('posts', [PostController::class, 'index']);
// Route::get('posts/create', [PostController::class, 'create']);
// Route::post('posts', [PostController::class, 'store']);
// Route::get('posts/{post}', [PostController::class, 'show']);
// Route::get('posts/{post}/edit', [PostController::class, 'edit']);
// Route::match(['put', 'patch'],'posts/{post}', [PostController::class, 'update']);
// Route::delete('posts/{post}', [PostController::class, 'destroy']);

Route::resource('posts', PostController::class);

//titikAssesoris
// Route::get('titikAssesoris', [TitikAssesorisController::class, 'index']);
// Route::get('titikAssesoris/create', [TitikAssesorisController::class, 'create']);
// Route::post('titikAssesoris', [TitikAssesorisController::class, 'store']);
// Route::get('titikAssesoris/{titikAssesoris}', [TitikAssesorisController::class, 'show']);
// Route::get('titikAssesoris/{titikAssesoris}/edit', [TitikAssesorisController::class, 'edit']);
// Route::match(['put', 'patch'],'titikAssesoris/{titikAssesoris}', [TitikAssesorisController::class, 'update']);
// Route::delete('titikAssesoris/{titikAssesoris}', [TitikAssesorisController::class, 'destroy']);


//JaringanPipa
Route::resource('jaringan-pipa', JaringanPipaController::class);

Route::get('geojson/{table}', [GeoJsonController::class, 'geojson']);
Route::get('peta', [GeoJsonController::class, 'peta']);

//TitikAssesoris
Route::resource('titik-assesoris', TitikAssesorisController::class);

Route::get('/pemasangan', [PublicPemasanganController::class, 'create'])->name('createPemasangan');
// Route::get('/pelaporan', [PublicPelaporanController::class, 'create'])->name('createPelaporan');
// Admin Routes
Route::prefix('admin')->middleware('auth')->group(function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('pemasangan', PemasanganController::class);
    // Route::resource('pelaporan', PelaporanController::class);
    //Route::resource('titik-assesoris', TitikAssesorisController::class);
});

app/Models/JaringanPipa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class JaringanPipa extends Model
{
    //use HasFactory;
    protected $table = 'update_september21';
    
    protected $guarded = [];

    protected $primaryKey = 'gid';

    public $timestamps = false;
}

app/Http/Controllers/JaringanPipaController.php
<?php

namespace App\Http\Controllers;

use App\Helper\Helper;
use App\Models\JaringanPipa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class JaringanPipaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $collection = JaringanPipa::all();
        return view('frontend/jaringanpipa', ['data' => $collection]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new JaringanPipa;
        return view('jaringanpipa.create', compact(
            'model'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:52'],
            'geom' => ['required', 'json'] // GeoJSON geometry
        ]);

        $model = new JaringanPipa;
        $model->name = $request->name;
        $model->kml_folder = $request->kml_folder;
        $model->diameter = $request->diameter;
        $model->panjang = $request->panjang;
        $model->tahun = $request->tahun;
        $model->_lokasi = $request->_lokasi;
        $model->geom = DB::raw("st_setsrid(st_multi(st_geomfromgeojson('$request->geom')), 4326)");
        $model->save();

        return redirect('jaringan-pipa');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\JaringanPipa  $jaringan_pipa
     * @return \Illuminate\Http\Response
     */
    public function show(JaringanPipa $jaringan_pipa)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\JaringanPipa  $jaringan_pipa
     * @return \Illuminate\Http\Response
     */
    public function edit(JaringanPipa $jaringan_pipa)
    {
       
        return view('frontend/jaringanpipa/edit',['model'=>$jaringan_pipa, 'geojson'=>Helper::modelToGeoJson($jaringan_pipa)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\JaringanPipa  $jaringan_pipa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, JaringanPipa $jaringan_pipa)
    {
      
        $jaringan_pipa->gid = $request->gid;
        $jaringan_pipa->name = $request->name;
        $jaringan_pipa->kml_folder = $request->kml_folder;
        $jaringan_pipa->diameter = $request->diameter;
        $jaringan_pipa->panjang = $request->panjang;
        $jaringan_pipa->tahun = $request->tahun;
        $jaringan_pipa->_lokasi = $request->_lokasi;
        $jaringan_pipa->geom = $request->geom;
        $jaringan_pipa->save();

        return redirect('jaringan-pipa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\JaringanPipa  $jaringan_pipa
     * @return \Illuminate\Http\Response
     */
    public function destroy(JaringanPipa $jaringan_pipa)
    {
       
        $jaringan_pipa->delete();
        return redirect('jaringan-pipa');
    }
}

resources/views/frontend/jaringanpipa/create.blade.php
@extends('frontend.layouts.app')

@section('content')
   <br/>
   <form methods="POST" action="{{url{'jaringan-pipa'}  }}">
    @csrf
    GID  <input type="text" name="gid"><br/>>
    Name <input type="text" name="name"><br/>>
    KML_folder <input type="text" name="kml_folder"><br/>>
    Diameter <input type="text" name="diameter"><br/>>
    Panjang  <input type="text" name="panjang"><br/>>
    Tahun <input type="text" name="tahun"><br/>>
    Lokasi <input type="text" name="_lokasi"><br/>>
    Geometry <input type="text" name="geom"><br/>>


    <button type="submit">SIMPAN</button>
   </form>
@endsection

resources/views/frontend/jaringanpipa/edit.blade.php
@extends('frontend.layouts.app')

@section('content')
    <br />
    <form methods="POST" action="{{ route('jaringan-pipa.update', $model->gid) }}">
        @csrf
        <input type="hidden" name="_method" value="PATCH">
        GID <input type="text" name="gid" value="{{ $model->gid }}"><br />
        Name <input type="text" name="name" value="{{ $model->name }}"><br />
        KML_folder <input type="text" name="kml_folder" value="{{ $model->kml_folder }}"><br />
        Diameter <input type="text" name="diameter" value="{{ $model->diameter }}"><br />
        Panjang <input type="text" name="panjang" value="{{ $model->panjang }}"><br />
        Tahun <input type="text" name="tahun" value="{{ $model->tahun }}"><br />
        Lokasi <input type="text" name="_lokasi" value="{{ $model->_lokasi }}"><br />
        Geometry
        <textarea name="geom" id="geom" cols="30" rows="5">@json($geojson['geometry'])</textarea>


        <button type="submit">SIMPAN</button>
    </form>

    <div id="map" style="width: 800px; height:400px;"></div>
@endsection

@push('css')
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
        crossorigin="" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet-draw@1.0.4/dist/leaflet.draw.css">
@endpush

@push('js')
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin=""></script>
    <script src="https://cdn.jsdelivr.net/npm/leaflet-draw@1.0.4/dist/leaflet.draw.min.js"></script>
    <script>
        const geojson = @json($geojson);
        const map1 = L.map('map').setView([-7, 110], 5);

        const basemap1 = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '<a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> ǀ <a href="PJSIG UGM" target="_blank">SIG UGM</a>' //menambahkan nama//
        });
        basemap1.addTo(map1);

        const layer = L.geoJSON(geojson);
        layer.addTo(map1);
        map1.fitBounds(layer.getBounds());

        const drawControl = new L.Control.Draw({
            draw: false,
            edit: {
                featureGroup: layer,
                remove: false
            }
        });
        map1.addControl(dra
        wControl);

        map1.on('draw:edited', e => {
            const layers = e.layers;
            const geomInput = document.getElementById('geom');
            layers.eachLayer(layer => {
                try {
                    geomInput.value = JSON.stringify(layer.toGeoJSON().geometry);
                } catch (error) {
                    console.error(error);
                    // TODO: Show error
                }
            });
        });
    </script>
@endpush